version: '3.8'

services:
  # BANCO
  db-auth-users:
    image: postgres:latest
    container_name: db-auth-users
    volumes:
      - postgres_data_auth:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: msauthusers
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    restart: always
    networks:
      - sgpism_network

# CONFIG NETWORKS
networks:
  sgpism_network:
    driver: bridge

volumes:
  postgres_data_auth:
