spring:
    application:
        name: msauthusers
    profiles:
        active: local
    cloud: 
        gateway: 
          mvc:          
            routes:
                - id: ms-pedidos
                  uri: http://localhost:8084
                  predicates:
                    - Path=/pedidos/**

                - id: ms-pagamentos
                  uri: http://localhost:8081
                  predicates:
                    - Path=/pagamentos/**

                - id: ms-produtos
                  uri: http://localhost:8082
                  predicates:
                    - Path=/produtos/**
                    
                - id: ms-carrinhos
                  uri: http://localhost:8083
                  predicates:
                    - Path=/carrinhos/**

server:
    port: 8080

msprodutos:
    url: http://localhost:8082

api:
    security:
        token:
            secret: ${JWT_SECRET:my-secret-key}

springdoc:
    api-docs:
        enabled: true
        path: /api-docs
    swagger-ui:
        path: /swagger-ui.html    
        defaultModelsExpandDepth: -1


