spring:
    application:
        name: msauthusers
    profiles:
        active: local
server:
    port: 8080

api:
    security:
        token:
            secret: ${JWT_SECRET:my-secret-key}

springdoc:
    api-docs:
        enabled: true
        path: /api-docs
    swagger-ui:
        path: /swagger-ui.html    
        defaultModelsExpandDepth: -1


