spring:
    datasource:
        url: jdbc:h2:mem:auth-users;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE;
        username: sa
    sql:
        init:
            mode: always
            data-locations: classpath:massaDeDados.sql
            encoding: UTF-8
    jpa:
        hibernate: 
            ddl-auto: create-drop
        defer-datasource-initialization: true
        properties:
            hibernate: 
                format_sql: true
                show_sql: true



