spring:
    application:
        name: msauthusers
    profiles:
        active: local
server:
    port: 8080

api:
    security:
        token:
            secret: ${JWT_SECRET:my-secret-key}

springdoc:
    swagger-ui:
        path: /swagger-${spring.application.name}
        defaultModelsExpandDepth: -1
        disable-swagger-default-url: true


