spring:
    datasource:
        url: jdbc:h2:mem:auth-users;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE;
        username: sa
    sql:
        init:
            mode: always
            data-locations: classpath:massaDeDados.sql
            encoding: UTF-8
    jpa:
        hibernate: 
            ddl-auto: create-drop
        defer-datasource-initialization: true
        properties:
            hibernate: 
                format_sql: true
                show_sql: true
    h2:
        console:
            enabled: true    
    cloud: 
        gateway: 
          mvc:          
            routes:
                - id: ms-pedidos
                  uri: http://mspedidos:8084
                  predicates:
                    - Path=/pedidos/**

                - id: ms-pagamentos
                  uri: http://mspagamentos:8081
                  predicates:
                    - Path=/pagamentos/**

                - id: ms-produtos
                  uri: http://msprodutos:8082
                  predicates:
                    - Path=/produtos/**
                    
                - id: ms-carrinhos
                  uri: http://mscarrinhos:8083
                  predicates:
                    - Path=/carrinhos/**

msprodutos:
    url: http://msprodutos:8082